spring:
  application:
    name: authorization
  datasource:
    url: jdbc:postgresql://localhost:5432/authorization
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
server:
  port: 9090
jwt:
  secret:
    access: N1IzSllnbDFOeFI0UmM5YkVicmRNNEp1bGNieHlRRks1eDlXbGVFMktjWT0=